#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  redLed,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  yellowLed,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  greenLed,       sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  flyEnc,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           intake,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           blWheel,       tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           flWheel,       tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           brWheel,       tmotorVex393HighSpeed_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port5,           frWheel,       tmotorVex393HighSpeed_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port6,           brFly,         tmotorVex393TurboSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port7,           trFly,         tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           blFly,         tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           tlFly,         tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          lift,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "rkUtil/lib.h"

#include "rkLcd/lib.h"

#include "rkLogic/dlatch.h"

#include "rkControl/base.h"
#include "rkControl/diff.h"
#include "rkControl/kalman.h"
#include "rkControl/tbh.h"
#include "rkControl/tbhController.h"

#define RKCOMP_LCD
//#define RKCOMP_DEBUG

#define RKCOMP_DEBUG_MENU_COND vexRT[Btn8R]
#define RKCOMP_DEBUG_DISABLE_COND vexRT[Btn8U]
#define RKCOMP_DEBUG_AUTON_COND vexRT[Btn8L]
#define RKCOMP_DEBUG_DRIVER_COND vexRT[Btn8D]
#define RKCOMP_DEBUG_RESTART_COND vexRT[Btn6U]

#include "rkCompetition/lib.h"

float flyLRPwr = 825,
	flySRPwr = 550;
const float velThresh = 50,
	accelThresh = 100;

ADiff flyDiff, fly2Diff;
KFlt fly2Flt;
Tbh flyTbh;
TbhController flyCtl;

#define PWR_BTN_DOWN ((nLCDButtons & kButtonLeft) || vexRT[Btn7D])
#define PWR_BTN_UP ((nLCDButtons & kButtonRight) || vexRT[Btn7U])

#define PWR_BTN_LRMODE vexRT[Btn7L]
#define PWR_BTN_SRMODE vexRT[Btn7R]

task lcd() {
	const float flyPwrIncrement = 5;
	const word battThresh = 7800;
	const long pwrBtnsDelayInterval = 750,
		pwrBtnsRepeatInterval = 100,
		dispPwrTimeout = 1000;

	bool dispPwr = false,
		doUseLRPwr = true,
		flash = false,
		forceBattWarning = true,
		pwrBtnsDown,
		pwrBtnsRepeating;

	float pwrBtns;
	long time = nSysTime, flashTs = time, dispPwrTs = time, pwrBtnTs = time;
	string str;

	DLatch dismissWarningLatch, pwrBtnLatch, pwrBtnLRModeLatch, pwrBtnSRModeLatch;

	while (true) {
		time = nSysTime;

		if (nImmediateBatteryLevel < battThresh) {
			if ((time - flashTs) >= 500) {
				flash = !flash;
				flashTs = time;
			}

			SensorValue[redLed] =
				SensorValue[yellowLed] =
				SensorValue[greenLed] = flash;
		}
		else {
			SensorValue[redLed] =
				SensorValue[yellowLed] =
				SensorValue[greenLed] = 0;
		}

		clearLCD();

		if (nLCDButtons & kButtonCenter) {
			bLCDBacklight = true;

			displayLCDCenteredString(0, "Battery:");

			sprintBatt(str);

			displayLCDString(1, 0, str);
		}
		else if (nImmediateBatteryLevel < battThresh && (rkBotDisabled || rkAutonMode || forceBattWarning)) {
			bLCDBacklight = flash;

			if (flash) displayLCDCenteredString(0, "BATTERY WARNING");

			sprintBatt(str);
			displayLCDString(1, 0, str);

			if (fallingEdge(&dismissWarningLatch, nLCDButtons || (abs(vexRT[AccelY]) > 63))) forceBattWarning = false;
		}
		else if (rkBotDisabled) {
			bLCDBacklight = false;

			displayLCDCenteredString(0, "Moosebot Mk. II");
			displayLCDCenteredString(1, "4800Buckets");
		}
		else if (rkAutonMode) {
			bLCDBacklight = true;

			displayLCDCenteredString(0, "BUCKETS MODE");
			displayLCDCenteredString(1, "ENGAGED");
		}
		else { //User op mode
			bLCDBacklight = true;

			pwrBtnsDown = PWR_BTN_DOWN ^ PWR_BTN_UP;
			risingEdge(&pwrBtnLatch, pwrBtnsDown);

			if (pwrBtnsDown || (PWR_BTN_LRMODE ^ PWR_BTN_SRMODE)) dispPwrTs = time;

			if (risingEdge(&pwrBtnLRModeLatch, PWR_BTN_LRMODE)) doUseLRPwr = true;
			if (risingEdge(&pwrBtnSRModeLatch, PWR_BTN_SRMODE)) doUseLRPwr = false;

			if (pwrBtnsDown) {
				dispPwrTs = time;

				if (pwrBtnLatch.out || (time - pwrBtnTs >= (pwrBtnsRepeating ? pwrBtnsRepeatInterval : pwrBtnsDelayInterval))) {
					pwrBtnTs = time;
					if (!pwrBtnsRepeating) pwrBtnsRepeating = true;

					pwrBtns = twoWay((nLCDButtons & kButtonLeft) || vexRT[Btn7D], -flyPwrIncrement, (nLCDButtons & kButtonRight) || vexRT[Btn7U], flyPwrIncrement);

					if (doUseLRPwr) flyLRPwr += pwrBtns;
					else flySRPwr += pwrBtns;
				}
			}

			if (time - dispPwrTs <= dispPwrTimeout) {
				if (doUseLRPwr) {
					displayLCDCenteredString(0, "Long  Power:");
					displayLCDNumber(1, 0, flyLRPwr);
				}
				else {
					displayLCDCenteredString(0, "Short Power:");
					displayLCDNumber(1, 0, flySRPwr);
				}
			}
			else if (flyTbh.doRun) {
				sprintf(str, "% 07.2f  % 07.2f",
					fmaxf(-999.99, fminf(999.99, flyDiff.out)),
					fmaxf(-999.99, fminf(999.99, flyTbh.err)));
				displayLCDString(0, 0, str);

				sprintf(str, "% 07.2f  % 07.2f",
					fmaxf(-999.99, fminf(999.99, fly2Flt.out)),
					fmaxf(-999.99, fminf(999.99, flyTbh.out)));
				displayLCDString(1, 0, str);

				SensorValue[redLed] =
					SensorValue[yellowLed] =
					SensorValue[greenLed] = 0;

				if (isTbhInThresh(&flyTbh, velThresh)) {
					if (isTbhDerivInThresh(&flyTbh, accelThresh)) SensorValue[greenLed] = 1;
					else  SensorValue[yellowLed] = 1;
				}
				else SensorValue[redLed] = 1;
			}
			else {
				sprintf(str, "%-8s%8s", "Speed", "Error");
				displayLCDString(0, 0, str);

				sprintf(str, "%-8s%8s", "Accel", "Out");
				displayLCDString(1, 0, str);
			}
		}

		wait1Msec(50);
	}
}

void startFlyTbh(bool doUseCtl) {
	resetDiff(&flyDiff, 0);
	resetDiff(&fly2Diff, 0);

	resetKFlt(&fly2Flt, 0, 1);

	if (doUseCtl) updateTbhController(&flyCtl, 0);
	else setTbhDoRun(&flyTbh, true);

	SensorValue[flyEnc] = 0;
}

void stopCtls() {
	setTbhDoRun(&flyTbh, false);

	stopCtlLoop();
}

void init() {
	initKFlt(&fly2Flt, 10);

	initTbh(&flyTbh, 5, .25, .15, 127, true);

	initTbhController(&flyCtl, &flyTbh, false);

	ctlLoopInterval = 50;
}

void updateCtl(float dt) {
	updateDiff(&flyDiff, SensorValue[flyEnc], dt);
	updateDiff(&fly2Diff, flyDiff.out, dt);

	updateKFlt(&fly2Flt, fly2Diff.out, dt);

	if (flyTbh.doUpdate)
		motor[brFly] = motor[trFly] =
			motor[blFly] = motor[tlFly] = updateTbh(&flyTbh, flyDiff.out, fly2Flt.out, dt);
}

task auton() { }

void endAuton() { }

task userOp() {
	startFlyTbh(true);
	startCtlLoop();

	const float cutFac = 3;

	DLatch cutLatch, flipLatch, tankLatch, flyLRLatch, flySRLatch;

	word driveA, driveB, flyDir = 0;

#define driveX driveA
#define driveY driveB
#define driveL driveA
#define driveR driveB

	resetDLatch(&cutLatch, 0);
	resetDLatch(&flipLatch, 0);
	resetDLatch(&tankLatch, 0);
	resetDLatch(&flyLRLatch, 0);
	resetDLatch(&flySRLatch, 0);

	while (true) {
		risingBistable(&flipLatch, vexRT[Btn8D]);

		if (risingBistable(&tankLatch, vexRT[Btn8L])) {
			driveL = vexRT[ChLY];
			driveR = vexRT[ChRY];

			if (flipLatch.out) {
				driveL ^= driveR;
				driveR ^= driveL;
				driveL ^= driveR;

				driveL *= -1;
				driveR *= -1;
			}
		}
		else {
			driveX = vexRT[ChRX];
			driveY = vexRT[ChLY];

			if (flipLatch.out) driveY *= -1;
		}

		if (risingBistable(&cutLatch, vexRT[Btn8U])) {
			driveX = (word)(driveX / cutFac);
			driveY = (word)(driveY / cutFac);
		}

		if (tankLatch.out) {
			tank4(driveL, driveR, flWheel, blWheel, frWheel, brWheel);
		}
		else {
			arcade4(driveX, driveY, flWheel, blWheel, frWheel, brWheel);
		}

		if (risingEdge(&flyLRLatch, vexRT[Btn5U]))
			flyDir = flyDir == 1 ? 0 : 1;

		if (risingEdge(&flySRLatch, vexRT[Btn5D]))
			flyDir = flyDir == 2 ? 0 : 2;

		switch (flyDir) {
			case 1: updateTbhController(&flyCtl, flyLRPwr); break;
			case 2: updateTbhController(&flyCtl, flySRPwr); break;
			default: updateTbhController(&flyCtl, 0); break;
		}

		motor[intake] = motor[lift] =
			joyDigi2(Btn6U, 127, Btn6D, -127);

		wait1Msec(25);
	}

#undef driveX
#undef driveY
#undef driveL
#undef driveR
}

void endUserOp() {
	stopCtls();
}
